name: Run tests

# Install dependencies and run tests
on:
  push:

  workflow_dispatch:
    inputs:
      desc:
        description: 'Message'
        required: true
        default: 'Manual build'

jobs:
  build:
    name: CI check
    runs-on: ubuntu-latest
    env:
      CACHE_KEY: 'ci'
      DOTENV_CONFIG_PATH: .env.test
    timeout-minutes: 5
    steps:
      - uses: actions/checkout@v5

      - name: Export .nvmrc to node version
        id: node-version
        run: echo "version=$(cat .nvmrc | sed 's/v//')" >> $GITHUB_OUTPUT

      - name: Use Node.js
        uses: actions/setup-node@v6
        with:
          node-version: ${{ steps.node-version.outputs.version }}

      # each workflow has its own isolated environment and they don't share cache with each other, so the key should be unique for the workflow to work properly
      - name: Check if node modules are cached
        uses: actions/cache@v4.3.0
        with:
          path: ./node_modules
          key: ${{ env.CACHE_KEY }}-node-modules-${{ hashFiles('**/yarn.lock') }}

      - name: Install dependencies
        run: yarn install --frozen-lockfile

      - name: Run format
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn format:check

      - name: Run tests
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn test

      - name: Run linters
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn lint

      - name: Run build
        if: ${{ github.ref != 'refs/heads/main' }}
        run: yarn build

      - name: Run Trivy fs scanner
        uses: aquasecurity/trivy-action@0.33.1
        with:
          scan-type: "fs"
          scan-ref: './'
          scanners: "vuln,secret,config"
          exit-code: "1"
          ignore-unfixed: true
          severity: "CRITICAL,HIGH"
          vuln-type: "os,library"
