name: Update .nvmrc to latest LTS

on:
  schedule:
    - cron: '0 0 * * 1' # runs every Monday at 0:00 

  workflow_dispatch:
    
permissions:
  contents: write
  pull-requests: write

jobs:
  update-nvmrc:
    runs-on: ubuntu-latest
    timeout-minutes: 5
    steps:
      - uses: codemask-labs/update-nvmrc-action@v1.3.0
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
